### PR TITLE
frontend: allow selecting (overriding) key/value deserializer for topics

### PR DESCRIPTION
**Pull request by rikimaru0345**
image
image

### CODE REVIEW

**Comment by weeco** [comment]
Why is the key and value column empty in your given screenshot?

**Comment by rikimaru0345** [comment]
Because I selected "none" for that screenshot in both key and value.

**Comment by rikimaru0345** [comment]
I tested various deserializers, works properly from what I can see.
Only (maybe) strange thing is when, for example, selecting "message pack" for a json topic, it will just not give you any content.
I mean, fine, but maybe some sort of additional message would be good? Some thing like:

"You forced using "MESSAGE PACK" deserializer, but it failed, that's why the content of the messages is empty."

**Review by weeco — APPROVED** [review]

**Comment by ivpanda** [comment]
Sharing thoughts here so they don't only live in Slack. 

## Deserializer change 

The thought is that we show it in the same area as filters: 

image

It's not ideal that filters are different to this/the two settings are in a different place, but the mechanism will do what we want: the cog will lead the user to the modal to change it, the 'x' will remove it.

It might be nice in future to combine filters and table settings somehow? 

## "Empty" error 

Is this an error or a warning? Either way, I'd like to only show it once even if many/all messages are empty. 

image

**Comment by weeco** [comment]
@ivpanda Should we always show these then, so that there's always one for key and one for value deserializer but they are set to "auto" in most cases?

**Comment by ivpanda** [comment]
@weeco  I'm not sure I understand. Do you mean that these are almost always changed?

**Comment by weeco** [comment]
A key/value deserializer strategy must always be chosen. By default we always chose the strategy "Auto" and I wondered whether this should be shown there as well then, or only if either key/value deviate from the default

**Comment by ivpanda** [comment]
Ah, right. I think this should only be shown if we deviate from the default.

**Comment by rikimaru0345** [comment]
As requested it looks like a tag now:

https://github.com/redpanda-data/console/assets/28133019/eec35d99-00f8-4673-8181-3b621fbb5cc3

**Comment by rikimaru0345** [comment]
Video above is outdated, this is how it looks like when the deserializers are set/active:

image

**Pull request merged**
