### PR TITLE
Add copy message to publish for Republishing an existing message

### PR DESCRIPTION
**Pull request by ying234**
Feature #232 
Add a copy message to publish menu item to copy the key and value to publish page.

### CODE REVIEW

**Comment by weeco** [comment]
Republishing a record as is requires copying other attributes such as the offset, partition, headers as well to be copied. I believe just copying key/value is only a slight advantage over what's already possible by copying the key & value individually into the new publish modal.

**Review by jvorcak — APPROVED** [review]

**Comment by jvorcak** [comment]
I've checked when it comes to code, I'll leave to @weeco to approve whether it makes sense or not to merge in this state.

**Comment by ying234** [comment]
> Republishing a record as is requires copying other attributes such as the offset, partition, headers as well to be copied. I believe just copying key/value is only a slight advantage over what's already possible by copying the key & value individually into the new publish modal.

For me, I was using such copy a lot and I need to open two browser tabs. One tab is for copy and another is for paste to the input. Every time with several extra clicks. So, this change can save me from these extra clicks.

**Comment by ying234** [comment]
> Republishing a record as is requires copying other attributes such as the offset, partition, headers as well to be copied. I believe just copying key/value is only a slight advantage over what's already possible by copying the key & value individually into the new publish modal.

Add message key and value encoding, and headers to the copying.

**Comment by ying234** [comment]
@weeco any more suggestion or comment?

**Pull request closed without merging**
