### PR TITLE
frontend: redpanda connect and kafka connect ux improvements for serverless

### PR DESCRIPTION
**Pull request by ajyoung**
This PR implements the improvements described in https://github.com/redpanda-data/console-enterprise/issues/455

- [x] Add transforms endpoint to list of endpoints to hide in serverless 
- [x] Make connectors sidebar link inactive on serverless clusters when the PipelineService (rpconnect) feature is inactive. This covers the case between when Redpanda Connect for serverless is implemented and when it is made available to customers
- [x] Remove Kafka Connect tab from UI for serverless clusters

### CODE REVIEW

**Comment by ajyoung** [comment]
@rikimaru0345 -- Thanks for your help on this PR. I checked the build for this branch in integration today. The removal of the Kafka Connect tab and the removal of the transforms sidebar link were both successful. However, making the Connectors sidebar link inactive when cloud.redpandaConnect.enabled is false was unsuccessful; the link was still visible and clickable. Is there something missing [here](https://github.com/redpanda-data/console/pull/1395/commits/375830a32fca45e41fa3171f614b4b5e559d0905#diff-8461a11f321e348e2d860ef97342924cb56b1aa747a051aa684a72613601d9a4R281-R283)?

**Comment by rikimaru0345** [comment]
After thinking about it more, I don't think the little helper function `routeVisibility()` will be able to do what you want.
You can make your own though.

If you have a way to test this in integration, please try the following, replace the entire route definition:

```

    MakeRoute<{}>('/connect-clusters', KafkaConnectOverview, 'Connectors', LinkIcon, true, () => {
        if (isServerless()) {
            // We are in serverless, there is no kafka connect so we can ignore it.
            // Here, we only care about the pipeline service and use that to decide whether or not to show the entry
            if (Feature.PipelineService)
                return { visible: true, disabledReasons: [] };
            
            // Pipeline service is not active? Hide entry
            return { visible: false, disabledReasons: [] };
        } else {
            // We are in cloud (dedicated or BYOC), or selfhosted
            // We always show the entry, if kafka connect is not enabled, the page will show a link to the documentation
            return { visible: true, disabledReasons: [] };
        } 
    }),
    
```

**Comment by ajyoung** [comment]
@rikimaru0345 -- Thanks for your help. See the last commit. It looks like it should work but I see no effect on the page. See https://main--redpanda-cloud.netlify.app/clusters/cqpq1qbh10ho72v6h6n0/connect-clusters. Can we maybe debug together on Friday or sometime next week?

**Comment by ajyoung** [comment]
Thanks for your help @rikimaru0345! Your last commit pushed it over the top!

https://github.com/user-attachments/assets/89ecc680-d44e-488a-8f02-0e90254479e9

**Review by jan-g — COMMENTED** [review]
LGTM (and a pleasantly small amount of conditional code here); I'll leave the approval to someone who knows what they're doing however.

**Review by rikimaru0345 — APPROVED** [review]

**Pull request merged**
