### PR TITLE
Information about estimation of the message count

### PR DESCRIPTION
**Pull request by jvorcak**
Fixes https://github.com/redpanda-data/console/issues/1064

Screenshot 2024-06-12 at 9 28 29
Screenshot 2024-06-12 at 9 28 27

I know @ivpanda wanted to use sentence case elsewhere, so I've used it here as well. Please let me know if I should change some phrasing.

### CODE REVIEW

**Comment by weeco** [comment]
I think the info tooltip behind the number looks weird. I'd either remove it and make it hoverable on the label (Estimated messages) or put the tooltip there instead. Personally I think info icons irritate too much and the explanation is not super important to learn about.

**Comment by rikimaru0345** [comment]
The code itself looks fine from my side.

As for the text itself, or icon placement: you two guys will need to figure that out.

**Comment by jvorcak** [comment]
@weeco I see your point, but on the other hand, it's good to have some clue that there is an additional info located somewhere. Otherwise it'll give me a feeling I need to hover over other stuff just to learn more. But I'm open to take whatever approach. WDYT @ivpanda?

**Comment by jvorcak** [comment]
Screenshot 2024-06-19 at 19 44 17

**Pull request merged**
